# @package _global_

defaults:
  - _self_
  - data: kbnet.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: kbnet.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ${paths.data_dir}/ckpts/benchmarking/kbnet-kitti.pth
